server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 302 /portal/;
    }

    location = /portal {
        return 302 /portal/;
    }

    location /portal/ {
        try_files $uri $uri/ /portal/index.html;
    }
}
